Scaffold browser testing
Why? A bug was able to make it to release.

Applying these changes to tag v3.2.0, the bug is captured and the tests fail:

```
3) uuid() returns a 36 char string:
unknown error: Illegal invocation
running chrome
Error: An unknown server-side error occurred while processing the command.
    at execute("return uuid();") - index.js:312:3
```